name: weforza
description: The WeForza App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # The following dependency provides local persistence.
  sembast: ^3.2.0

  # For OS-specific directory paths.
  path_provider: ^2.0.9
  path: ^1.8.0

  # UUID generator for globally unique ids.
  uuid: ^3.0.6

  # The intl package provides translation utilities.
  intl: ^0.17.0

  # Jiffy provides better support for manipulating dates than the current Dart spec.
  jiffy: ^5.0.0

  # RxDart provides extensions to Dart Streams.
  rxdart: ^0.27.3

  # This package provides platform independent file picking.
  file_picker: ^4.5.0

  # This package provides Bluetooth Low Energy functionality.
  flutter_blue_plus: ^1.1.2

  # This package provides easy access to app settings.
  app_settings: ^4.1.1

  # The permission_handler packages provides utilities for requesting permissions.
  permission_handler: ^9.2.0

  # package_info_plus provides access to app specific information such as build number & version.
  package_info_plus: ^1.4.0

  # For shard state management.
  flutter_riverpod: ^1.0.3

  file: ^6.1.2

dev_dependencies:
  file_testing: 3.0.0

  flutter_lints: ^2.0.1

  test: any

  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_intl:
  enabled: true
