name: weforza
description: The WeForza App
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  # This package provides easy access to app settings.
  app_settings: ^5.1.1

  # Collection utilities.
  collection: ^1.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # Provides an injectable file system abstraction.
  # Used by tests.
  file: ^7.0.0

  # This package provides platform independent file picking.
  file_picker: ^8.0.3

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # For shared state management.
  flutter_riverpod: ^2.4.10

  # For picking images from the camera / gallery.
  image_picker: ^1.1.1

  # The intl package provides translation utilities.
  intl: any

  # This package provies MIME-type lookup utilities.
  mime: ^1.0.5

  # package_info_plus provides access to app specific information such as build number & version.
  package_info_plus: ^8.0.0

  # Path utilities for URI's and the like.
  path: ^1.8.1

  # For OS-specific directory paths.
  path_provider: ^2.1.3

  # RxDart provides extensions to Dart Streams.
  rxdart: ^0.27.7

  # The following dependency provides local persistence.
  sembast: ^3.6.0

  # UUID generator for globally unique ids.
  uuid: ^4.3.3

dev_dependencies:
  file_testing: 3.0.0

  flutter_driver:
    sdk: flutter

  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  
  test: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
