org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
# TODO: https://github.com/flutter/flutter/issues/184410
android.r8.proguardAndroidTxt.disallowed=false
# TODO: https://github.com/flutter/flutter/issues/184410
android.proguard.failOnMissingFiles=false

